"""Tests for the ambience in app/show/bed.py — the world outside the lab, read from Sounds/ambience/ambience.json.

The ambience is read by the static bed's functions, given its folder and manifest: a usable manifest gives the clips
the disk holds, each with its gain and its kind (texture or spot); an entry with any other kind is skipped. The
story's ambience.yaml chooses the clips that play, as bed.yaml does, and keeps their kinds. Only a clip the manifest
lists and the disk holds is served. The shipped ambience (Sounds/ambience/ and the story's ambience.yaml, both in the
repo) must agree: every clip the story enables is on disk and in the manifest with a kind, there are textures and
spots, every clip is CC0 (generated by the project; the app is MIT), and CREDITS.md names each one.
"""

import json
import logging
from pathlib import Path

from app.show.bed import AMBIENCE_MANIFEST, KINDS, bed_clips, bed_play_list, clip_path
from app.show.story import BedClip, _load_bed

REPO = Path(__file__).resolve().parent.parent


def _write(folder, clips, files=None):
    """An ambience manifest listing clips (each a dict as ambience.json holds it), and a small file for each name."""
    folder.mkdir(parents=True, exist_ok=True)
    for name in files if files is not None else [c["file"] for c in clips]:
        (folder / name).write_bytes(b"ID3")
    (folder / AMBIENCE_MANIFEST).write_text(json.dumps({"loudness_dbfs": -20, "clips": clips}), encoding="utf-8")


class TestAmbienceClips:
    def test_the_clips_of_the_manifest_with_their_gains_and_kinds(self, tmp_path):
        _write(tmp_path, [{"file": "dead-1.mp3", "gain": 1.5, "kind": "texture"},
                          {"file": "gun-1.mp3", "gain": 0.5, "kind": "spot"}])

        assert bed_clips(tmp_path, AMBIENCE_MANIFEST) == [{"file": "dead-1.mp3", "gain": 1.5, "kind": "texture"},
                                                          {"file": "gun-1.mp3", "gain": 0.5, "kind": "spot"}]

    def test_an_entry_of_another_kind_is_skipped_with_a_warning(self, tmp_path, caplog):
        _write(tmp_path, [{"file": "a.mp3", "gain": 1, "kind": "loop"}, {"file": "b.mp3", "gain": 1, "kind": "spot"}])

        with caplog.at_level(logging.WARNING):
            clips = bed_clips(tmp_path, AMBIENCE_MANIFEST, "The ambience")

        assert [c["file"] for c in clips] == ["b.mp3"]
        assert "The ambience skips an entry" in caplog.text

    def test_the_bed_reads_its_own_manifest_not_the_ambiences(self, tmp_path):
        _write(tmp_path, [{"file": "dead-1.mp3", "gain": 1, "kind": "texture"}])

        assert bed_clips(tmp_path) == []


class TestAmbiencePlayList:
    ON_DISK = [{"file": "dead-1.mp3", "gain": 2.0, "kind": "texture"}, {"file": "gun-1.mp3", "gain": 1.0, "kind": "spot"}]

    def test_the_storys_choice_keeps_each_clips_kind(self):
        chosen = (BedClip("gun-1.mp3", gain_db=-6), BedClip("dead-1.mp3", enabled=False))

        assert bed_play_list(self.ON_DISK, chosen) == [{"file": "gun-1.mp3", "gain": 0.5012, "kind": "spot"}]

    def test_a_clip_the_story_enables_but_the_disk_lacks_is_skipped_and_named(self, caplog):
        with caplog.at_level(logging.WARNING):
            clips = bed_play_list(self.ON_DISK, (BedClip("rain-1.mp3"),), "The ambience", "ambience.json")

        assert clips == []
        assert "The ambience skips rain-1.mp3" in caplog.text and "ambience.json" in caplog.text


class TestAmbienceClipPath:
    def test_a_listed_clip_on_disk_and_nothing_else(self, tmp_path):
        _write(tmp_path, [{"file": "dead-1.mp3", "gain": 1, "kind": "texture"}], files=["dead-1.mp3", "other.mp3"])

        assert clip_path(tmp_path, "dead-1.mp3", AMBIENCE_MANIFEST) == tmp_path / "dead-1.mp3"
        assert clip_path(tmp_path, "other.mp3", AMBIENCE_MANIFEST) is None
        assert clip_path(tmp_path, "dead-1.mp3") is None  # The bed's manifest does not list it


class TestStoryAmbience:
    def test_a_malformed_ambience_yaml_names_its_own_file(self, tmp_path):
        path = tmp_path / "ambience.yaml"
        path.write_text("clips:\n  - {file: dead-1.mp3, enable: false}\n", encoding="utf-8")

        try:
            _load_bed("lab-outbreak", path)
        except Exception as exc:  # StoryError
            assert "ambience.yaml does not know enable" in str(exc)
        else:
            raise AssertionError("a misspelled key must fail")

    def test_keywords_kept_in_lowercase_with_single_spaces(self, tmp_path):
        path = tmp_path / "ambience.yaml"
        path.write_text("clips:\n  - {file: boom-1.mp3, keywords: [Explosion, '  Lightning   Strikes ', dead's]}\n"
                        "  - {file: dead-1.mp3}\n", encoding="utf-8")

        clips = _load_bed("lab-outbreak", path, keywords=True)

        assert [c.keywords for c in clips] == [("explosion", "lightning strikes", "dead's"), ()]

    def test_cue_only_kept_false_by_default(self, tmp_path):
        path = tmp_path / "ambience.yaml"
        path.write_text("clips:\n  - {file: heli-1.mp3, keywords: [helicopter], cue_only: true}\n"
                        "  - {file: dead-1.mp3}\n", encoding="utf-8")

        clips = _load_bed("lab-outbreak", path, keywords=True)

        assert [c.cue_only for c in clips] == [True, False]

    def test_cue_only_must_be_true_or_false_and_needs_keywords(self, tmp_path):
        path = tmp_path / "ambience.yaml"
        for entry, why in (("{file: heli-1.mp3, keywords: [helicopter], cue_only: yes please}", "needs cue_only true or false"),
                           ("{file: heli-1.mp3, cue_only: true}", "cue_only without keywords"),
                           ("{file: heli-1.mp3, keywords: [], cue_only: true}", "cue_only without keywords")):
            path.write_text(f"clips:\n  - {entry}\n", encoding="utf-8")
            try:
                _load_bed("lab-outbreak", path, keywords=True)
            except Exception as exc:  # StoryError
                assert why in str(exc), (entry, str(exc))
            else:
                raise AssertionError(f"{entry} must fail")

    def test_cue_only_only_in_the_ambience(self, tmp_path):
        path = tmp_path / "bed.yaml"
        path.write_text("clips:\n  - {file: static-1.mp3, cue_only: false}\n", encoding="utf-8")

        try:
            _load_bed("lab-outbreak", path)
        except Exception as exc:  # StoryError
            assert "bed.yaml does not know cue_only" in str(exc)
        else:
            raise AssertionError("cue_only in bed.yaml must fail")

    def test_keywords_only_in_the_ambience(self, tmp_path):
        path = tmp_path / "bed.yaml"
        path.write_text("clips:\n  - {file: static-1.mp3, keywords: [static]}\n", encoding="utf-8")

        try:
            _load_bed("lab-outbreak", path)
        except Exception as exc:  # StoryError
            assert "bed.yaml does not know keywords" in str(exc)
        else:
            raise AssertionError("keywords in bed.yaml must fail")

    def test_keywords_must_be_a_list_of_words_or_phrases(self, tmp_path):
        path = tmp_path / "ambience.yaml"
        for keywords, why in (("explosion", "needs keywords a list"), ("[boom!]", "needs keywords of letters only"),
                              ("[3 shots]", "needs keywords of letters only"), ("[42]", "needs keywords a list")):
            path.write_text(f"clips:\n  - {{file: boom-1.mp3, keywords: {keywords}}}\n", encoding="utf-8")
            try:
                _load_bed("lab-outbreak", path, keywords=True)
            except Exception as exc:  # StoryError
                assert why in str(exc), (keywords, str(exc))
            else:
                raise AssertionError(f"keywords {keywords} must fail")


class TestShippedAmbience:
    """The ambience as shipped: Sounds/ambience/ and the story's ambience.yaml, both in the repo."""

    FOLDER = REPO / "Sounds" / "ambience"

    def _manifest(self):
        return json.loads((self.FOLDER / AMBIENCE_MANIFEST).read_text(encoding="utf-8"))["clips"]

    def test_every_clip_the_story_enables_is_on_disk_and_in_the_manifest_with_a_kind(self):
        chosen = _load_bed("lab-outbreak", REPO / "stories" / "lab-outbreak" / "ambience.yaml", keywords=True)
        on_disk = bed_clips(self.FOLDER, AMBIENCE_MANIFEST)
        enabled = [c.file for c in chosen if c.enabled]
        assert enabled, "the shipped story enables no clip of the ambience"
        playing = bed_play_list(on_disk, chosen)
        assert [c["file"] for c in playing] == enabled
        assert all(c.get("kind") in KINDS for c in playing)

    def test_the_shipped_keywords_cue_only_enabled_clips_on_disk(self):
        chosen = _load_bed("lab-outbreak", REPO / "stories" / "lab-outbreak" / "ambience.yaml", keywords=True)
        on_disk = {c["file"] for c in bed_clips(self.FOLDER, AMBIENCE_MANIFEST)}
        cued = [c.file for c in chosen if c.keywords]
        assert cued, "the shipped story gives no clip keywords"
        assert all(c.enabled and c.file in on_disk for c in chosen if c.keywords)

    def test_there_are_textures_and_spots(self):
        kinds = {c["kind"] for c in self._manifest()}
        assert kinds == set(KINDS), kinds

    def test_every_shipped_clip_is_cc0(self):
        clips = self._manifest()
        barred = [c["file"] for c in clips if c.get("licence") != "CC0 1.0"]
        assert clips and not barred, f"ambience clips not released as CC0: {barred}"

    def test_credits_name_every_clip_and_its_licence(self):
        credits = (self.FOLDER / "CREDITS.md").read_text(encoding="utf-8")
        assert "CC0 1.0" in credits
        for clip in self._manifest():
            assert f"`{clip['file']}`" in credits, clip["file"]
